import { expect, test } from '@playwright/test'

test('header exposes new sections and icon search with keyboard focus restoration', async ({ page }) => {
  await page.goto('/')
  const nav = page.getByRole('navigation', { name: '主导航' })
  await expect(nav.getByRole('link')).toHaveText(['归档', '项目', '学术', '关于', '朋友们'])
  await expect(nav.getByRole('link', { name: '首页', exact: true })).toHaveCount(0)
  const trigger = page.getByRole('link', { name: '搜索', exact: true })
  await trigger.focus()
  await page.keyboard.press('Control+k')
  const dialog = page.getByRole('dialog', { name: '找一点感兴趣的' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('searchbox')).toBeFocused()
  await dialog.getByRole('searchbox').fill('Astro')
  await expect(dialog.getByRole('link', { name: /Astro 内容架构/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await nav.getByRole('link', { name: '学术', exact: true }).click()
  await expect(page).toHaveURL(/\/academic\/$/)
  await page.keyboard.press('Meta+k')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('searchbox')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await trigger.click()
  await expect(dialog.getByRole('searchbox')).toBeFocused()
  await expect(page).toHaveURL(/\/academic\/$/)
  await dialog.getByRole('link', { name: '打开完整搜索页 →' }).click()
  await expect(page).toHaveURL(/\/search\/$/)
  await expect(page.getByRole('searchbox')).toBeVisible()
  await expect(page.locator('html')).not.toHaveCSS('overflow', 'hidden')
})

test('new public pages preserve contact details and have no horizontal overflow', async ({ page }) => {
  for (const path of ['/academic/', '/home/', '/friends/', '/about/']) {
    await page.goto(path)
    await expect(page.getByRole('heading', { level: 1 })).toHaveCount(1)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect(page.locator('link[rel="icon"]')).toHaveAttribute('href', '/favicon.svg')
  }
  await page.goto('/home/')
  await expect(page.getByRole('link', { name: 'funni8034@gmail.com', exact: true })).toHaveAttribute('href', 'mailto:funni8034@gmail.com')
  await expect(page.getByRole('link', { name: '1411854675@qq.com', exact: true })).toHaveAttribute('href', 'mailto:1411854675@qq.com')
  await expect(page.locator('#contact')).toContainText('810225302')
  await page.goto('/academic/')
  await expect(page.getByRole('heading', { name: '脉冲神经网络' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '多智能体强化学习' })).toBeVisible()
  await expect(page.getByText('暂时留白，等新的想法慢慢长出来。')).toBeVisible()
})

test('quick search failure provides a usable fallback and closes normally', async ({ page }) => {
  await page.route('**/pagefind/pagefind-ui.js', route => route.abort())
  await page.goto('/home/')
  await page.getByRole('link', { name: '搜索', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('status')).toContainText('搜索暂时无法加载')
  await expect(dialog.getByRole('link', { name: '打开完整搜索页 →' })).toBeVisible()
  await expect(dialog.getByRole('link', { name: '浏览文章归档 →' })).toHaveAttribute('href', '/archives/')
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
})
