FROM lizheming/waline:1.41.4@sha256:a3c87cb50fdb3aa786d73ac7afed492811d5dbc217866b12f3d5a4eda5c5e4bc

COPY server/rate-limit.cjs /app/rate-limit.cjs
COPY server/config.cjs /app/node_modules/@waline/vercel/config.js
